<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Arguments -->
  <xacro:arg name="use_ros2_control" default="true"/>
  <xacro:arg name="use_sim_time" default="true"/>

  <!-- Include common macros -->
  <xacro:include filename="$(find my_robot_description)/urdf/macros.xacro"/>

  <!-- Robot base properties -->
  <xacro:property name="base_radius" value="0.3"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <!-- Wheel positions for 3-wheeled omnidirectional robot -->
  <!-- Wheels positioned at 120 degrees apart -->
  <xacro:property name="wheel_1_x" value="${base_radius * 0.866}"/> <!-- cos(30°) -->
  <xacro:property name="wheel_1_y" value="${base_radius * 0.5}"/>   <!-- sin(30°) -->
  <xacro:property name="wheel_2_x" value="${-base_radius * 0.866}"/> <!-- -cos(30°) -->
  <xacro:property name="wheel_2_y" value="${base_radius * 0.5}"/>   <!-- sin(30°) -->
  <xacro:property name="wheel_3_x" value="0"/>
  <xacro:property name="wheel_3_y" value="${-base_radius}"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.3 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.2"/>
    </inertial>
  </link>

  <!-- Omni wheels -->
  <xacro:macro name="omni_wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.005" ixy="0.0" ixz="0.0"
                 iyy="0.005" iyz="0.0"
                 izz="0.01"/>
      </inertial>
    </link>

    <!-- Joint connecting wheel to base -->
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Omni wheel rollers (simplified as passive joints) -->
    <link name="${name}_roller_link">
      <visual>
        <geometry>
          <cylinder length="0.01" radius="0.02"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.02"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.002"/>
      </inertial>
    </link>

    <!-- Passive joint for rollers -->
    <joint name="${name}_roller_joint" type="continuous">
      <parent link="${name}_link"/>
      <child link="${name}_roller_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <xacro:if condition="$(arg use_ros2_control)">
      <!-- ROS 2 Control interface for wheel -->
      <ros2_control name="${name}_wheel_controller" type="system">
        <hardware>
          <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <joint name="${name}_joint">
          <command_interface name="velocity"/>
          <state_interface name="velocity"/>
          <state_interface name="position"/>
        </joint>
      </ros2_control>
    </xacro:if>
  </xacro:macro>

  <!-- Create three omni wheels -->
  <xacro:omni_wheel name="wheel_1" x="${wheel_1_x}" y="${wheel_1_y}"/>
  <xacro:omni_wheel name="wheel_2" x="${wheel_2_x}" y="${wheel_2_y}"/>
  <xacro:omni_wheel name="wheel_3" x="${wheel_3_x}" y="${wheel_3_y}"/>

  <!-- Laser frame (RPLidar position) -->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.08"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.2 0.2 1.0"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.08"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.002"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${base_height + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- IMU frame -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
      <material name="green">
        <color rgba="0.2 0.8 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0002"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.05 0 ${base_height - 0.01}" rpy="0 0 0"/>
  </joint>

  <!-- Camera frame -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.04 0.03"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.04 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
               iyy="0.0005" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_radius - 0.02} 0 ${base_height + 0.03}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo plugins -->
  <gazebo>
    <!-- Differential drive plugin for omnidirectional movement -->
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace></namespace>
        <remapping>cmd_vel:=/diff_drive_controller/cmd_vel_unstamped</remapping>
        <remapping>odom:=/diff_drive_controller/odom</remapping>
      </ros>

      <!-- Wheel configuration for 3-wheeled omnidirectional robot -->
      <wheel_1_joint>wheel_1_joint</wheel_1_joint>
      <wheel_2_joint>wheel_2_joint</wheel_2_joint>
      <wheel_3_joint>wheel_3_joint</wheel_3_joint>

      <!-- Wheel properties -->
      <wheel_separation>${base_radius * 1.732}</wheel_separation> <!-- 2 * sin(60°) * radius -->
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <!-- Robot properties -->
      <robot_base_frame>base_link</robot_base_frame>
      <wheel_torque>20.0</wheel_torque>
      <wheel_acceleration>1.0</wheel_acceleration>

      <!-- Odometry properties -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
      <odometry_topic>odom</odometry_topic>

      <!-- Command timeout -->
      <cmd_timeout>0.25</cmd_timeout>

      <!-- Legacy mode (for compatibility) -->
      <legacy_mode>false</legacy_mode>
    </plugin>

    <!-- IMU sensor plugin -->
    <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>imu/data:=/imu/data</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>50.0</update_rate>
      <body_name>imu_link</body_name>
      <topic_name>imu/data</topic_name>
      <gaussian_noise>0.001</gaussian_noise>
      <frame_name>imu_link</frame_name>
    </plugin>

    <!-- Laser scan plugin -->
    <plugin name="laser_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>scan:=/scan</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <topic_name>scan</topic_name>
      <frame_name>laser_frame</frame_name>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <!-- Camera plugin -->
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <ros>
        <namespace></namespace>
        <remapping>image_raw:=/camera/image_raw</remapping>
        <remapping>camera_info:=/camera/camera_info</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera_name>camera</camera_name>
      <frame_name>camera_link</frame_name>
      <image_topic_name>image_raw</image_topic_name>
      <camera_info_topic_name>camera_info</camera_info_topic_name>
      <hack_baseline>0.07</hack_baseline>
    </plugin>

    <!-- Contact sensor for ground detection -->
    <plugin name="ground_contact" filename="libgazebo_ros_bumper.so">
      <ros>
        <namespace></namespace>
        <remapping>bumper:=/bumper</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <bumper_topic_name>bumper</bumper_topic_name>
      <frame_name>base_link</frame_name>
    </plugin>
  </gazebo>

</robot>
