<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Arguments -->
  <xacro:arg name="use_ros2_control" default="true"/>
  <xacro:arg name="use_sim_time" default="true"/>

  <!-- Macros defined below -->

  <!-- Robot base properties -->
  <xacro:property name="base_radius" value="0.3"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <!-- Wheel positions for 3-wheeled omnidirectional robot -->
  <!-- Wheels positioned at 120 degrees apart -->
  <xacro:property name="wheel_1_x" value="${base_radius * 0.866}"/> <!-- cos(30째) -->
  <xacro:property name="wheel_1_y" value="${base_radius * 0.5}"/>   <!-- sin(30째) -->
  <xacro:property name="wheel_2_x" value="${-base_radius * 0.866}"/> <!-- -cos(30째) -->
  <xacro:property name="wheel_2_y" value="${base_radius * 0.5}"/>   <!-- sin(30째) -->
  <xacro:property name="wheel_3_x" value="0"/>
  <xacro:property name="wheel_3_y" value="${-base_radius}"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.3 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.2"/>
    </inertial>
  </link>

  <!-- Omni wheels -->
  <xacro:macro name="omni_wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.005" ixy="0.0" ixz="0.0"
                 iyy="0.005" iyz="0.0"
                 izz="0.01"/>
      </inertial>
    </link>

    <!-- Joint connecting wheel to base -->
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Omni wheel rollers (simplified as passive joints) -->
    <link name="${name}_roller_link">
      <visual>
        <geometry>
          <cylinder length="0.01" radius="0.02"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.02"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.002"/>
      </inertial>
    </link>

    <!-- Passive joint for rollers -->
    <joint name="${name}_roller_joint" type="continuous">
      <parent link="${name}_link"/>
      <child link="${name}_roller_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <xacro:if value="$(arg use_ros2_control)">
      <!-- ROS 2 Control interface for wheel -->
      <ros2_control name="${name}_wheel_controller" type="system">
        <hardware>
          <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <joint name="${name}_joint">
          <command_interface name="velocity"/>
          <state_interface name="velocity"/>
          <state_interface name="position"/>
        </joint>
      </ros2_control>
    </xacro:if>
  </xacro:macro>

  <!-- Create three omni wheels -->
  <xacro:omni_wheel name="wheel_1" x="${wheel_1_x}" y="${wheel_1_y}"/>
  <xacro:omni_wheel name="wheel_2" x="${wheel_2_x}" y="${wheel_2_y}"/>
  <xacro:omni_wheel name="wheel_3" x="${wheel_3_x}" y="${wheel_3_y}"/>

  <!-- LIDAR frame -->
  <link name="lidar_frame">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.08"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.2 0.2 1.0"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.08"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.002"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_frame"/>
    <origin xyz="0 0 ${base_height + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- Ultrasonic Sensors (4x) -->
  <xacro:macro name="ultrasonic_sensor" params="name x y z">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder length="0.02" radius="0.015"/>
        </geometry>
        <material name="yellow">
          <color rgba="1.0 1.0 0.0 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.02" radius="0.015"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0002"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- IR Sharp Sensors (3x) -->
  <xacro:macro name="ir_sensor" params="name x y z">
    <link name="${name}_link">
      <visual>
        <geometry>
          <box size="0.02 0.02 0.015"/>
        </geometry>
        <material name="orange">
          <color rgba="1.0 0.5 0.0 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.02 0.02 0.015"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.03"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0002"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Line Sensor -->
  <link name="line_sensor_link">
    <visual>
      <geometry>
        <box size="0.08 0.03 0.01"/>
      </geometry>
      <material name="purple">
        <color rgba="0.8 0.0 0.8 1.0"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.08 0.03 0.01"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.02"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0002"/>
    </inertial>
  </link>

  <joint name="line_sensor_joint" type="fixed">
    <parent link="base_link"/>
    <child link="line_sensor_link"/>
    <origin xyz="0 0 -${base_height/2 - 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Create ultrasonic sensors -->
  <xacro:ultrasonic_sensor name="ultrasonic_front" x="${base_radius - 0.02}" y="0" z="${base_height/2}"/>
  <xacro:ultrasonic_sensor name="ultrasonic_back" x="${-base_radius + 0.02}" y="0" z="${base_height/2}"/>
  <xacro:ultrasonic_sensor name="ultrasonic_left" x="0" y="${base_radius - 0.02}" z="${base_height/2}"/>
  <xacro:ultrasonic_sensor name="ultrasonic_right" x="0" y="${-base_radius + 0.02}" z="${base_height/2}"/>

  <!-- Create IR sensors -->
  <xacro:ir_sensor name="ir_front" x="${base_radius - 0.05}" y="0" z="${base_height/2}"/>
  <xacro:ir_sensor name="ir_left" x="0" y="${base_radius - 0.05}" z="${base_height/2}"/>
  <xacro:ir_sensor name="ir_right" x="0" y="${-base_radius + 0.05}" z="${base_height/2}"/>

  <!-- IMU frame -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
      <material name="green">
        <color rgba="0.2 0.8 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0002"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.05 0 ${base_height - 0.01}" rpy="0 0 0"/>
  </joint>

  <!-- Camera frame -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.04 0.03"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.04 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
               iyy="0.0005" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_radius - 0.02} 0 ${base_height + 0.03}" rpy="0 0 0"/>
  </joint>

  <!-- Lifter/Forklift (1x DC Motor + Encoder) -->
  <link name="lifter_link">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.3"/>
      </geometry>
      <material name="silver">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.1 0.1 0.3"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.05"/>
    </inertial>
  </link>

  <joint name="lifter_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="lifter_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100.0" lower="0.0" upper="0.1" velocity="0.1"/>
  </joint>

  <!-- Servo Motors (5x) -->
  <xacro:macro name="servo_joint" params="name x y z roll pitch yaw">
    <link name="${name}_link">
      <visual>
        <geometry>
          <box size="0.03 0.03 0.04"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.3 0.8 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.03 0.03 0.04"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0002"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="revolute">
      <parent link="lifter_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
      <axis xyz="0 0 1"/>
      <limit effort="10.0" lower="-3.14159" upper="3.14159" velocity="1.0"/>
    </joint>
  </xacro:macro>

  <!-- Create servo joints -->
  <xacro:servo_joint name="servo_1" x="0.05" y="0" z="0.15" roll="0" pitch="0" yaw="0"/>
  <xacro:servo_joint name="servo_2" x="0.08" y="0" z="0.15" roll="0" pitch="0" yaw="0"/>
  <xacro:servo_joint name="servo_3" x="0.11" y="0" z="0.15" roll="0" pitch="0" yaw="0"/>
  <xacro:servo_joint name="servo_4" x="0.14" y="0" z="0.15" roll="0" pitch="0" yaw="0"/>
  <xacro:servo_joint name="servo_5" x="0.17" y="0" z="0.15" roll="0" pitch="0" yaw="0"/>

  <!-- Gazebo plugins -->
  <gazebo>
    <!-- Differential drive plugin (simplified for basic movement) -->
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace></namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=/odom</remapping>
      </ros>

      <!-- Use only two wheels for basic differential drive -->
      <left_joint>wheel_1_joint</left_joint>
      <right_joint>wheel_2_joint</right_joint>

      <!-- Wheel properties -->
      <wheel_separation>${base_radius * 1.732}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <!-- Robot properties -->
      <robot_base_frame>base_link</robot_base_frame>
      <wheel_torque>20.0</wheel_torque>
      <wheel_acceleration>1.0</wheel_acceleration>

      <!-- Odometry properties -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
      <odometry_topic>odom</odometry_topic>

      <!-- Command timeout -->
      <cmd_timeout>0.25</cmd_timeout>

      <!-- Legacy mode (for compatibility) -->
      <legacy_mode>false</legacy_mode>
    </plugin>

    <!-- IMU sensor plugin -->
    <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>imu/data:=/imu/data</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>50.0</update_rate>
      <body_name>imu_link</body_name>
      <topic_name>imu/data</topic_name>
      <gaussian_noise>0.001</gaussian_noise>
      <frame_name>imu_link</frame_name>
    </plugin>

    <!-- LIDAR plugin -->
    <plugin name="lidar_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>scan:=/scan</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <topic_name>scan</topic_name>
      <frame_name>lidar_frame</frame_name>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <!-- Ultrasonic sensor plugins (4x) -->
    <plugin name="ultrasonic_front_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ultrasonic/front</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ultrasonic_front_link</frame_name>
      <ray>
        <range>
          <min>0.02</min>
          <max>4.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <plugin name="ultrasonic_back_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ultrasonic/back</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ultrasonic_back_link</frame_name>
      <ray>
        <range>
          <min>0.02</min>
          <max>4.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <plugin name="ultrasonic_left_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ultrasonic/left</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ultrasonic_left_link</frame_name>
      <ray>
        <range>
          <min>0.02</min>
          <max>4.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <plugin name="ultrasonic_right_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ultrasonic/right</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ultrasonic_right_link</frame_name>
      <ray>
        <range>
          <min>0.02</min>
          <max>4.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </plugin>

    <!-- IR Sharp sensor plugins (3x) -->
    <plugin name="ir_front_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ir/front</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ir_front_link</frame_name>
      <ray>
        <range>
          <min>0.04</min>
          <max>0.8</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
    </plugin>

    <plugin name="ir_left_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ir/left</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ir_left_link</frame_name>
      <ray>
        <range>
          <min>0.04</min>
          <max>0.8</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
    </plugin>

    <plugin name="ir_right_plugin" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <namespace></namespace>
        <remapping>range:=/ir/right</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <topic_name>range</topic_name>
      <frame_name>ir_right_link</frame_name>
      <ray>
        <range>
          <min>0.04</min>
          <max>0.8</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
    </plugin>

    <!-- Camera plugin -->
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <ros>
        <namespace></namespace>
        <remapping>image_raw:=/camera/image_raw</remapping>
        <remapping>camera_info:=/camera/camera_info</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera_name>camera</camera_name>
      <frame_name>camera_link</frame_name>
      <image_topic_name>image_raw</image_topic_name>
      <camera_info_topic_name>camera_info</camera_info_topic_name>
      <hack_baseline>0.07</hack_baseline>
    </plugin>

    <!-- Contact sensor for ground detection -->
    <plugin name="ground_contact" filename="libgazebo_ros_bumper.so">
      <ros>
        <namespace></namespace>
        <remapping>bumper:=/bumper</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <bumper_topic_name>bumper</bumper_topic_name>
      <frame_name>base_link</frame_name>
    </plugin>
  </gazebo>

</robot>
